version: '3'
services:
  db: 
    image: postgres:14 
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  data: