"""empty message

Revision ID: 0d5c1cd6f0c8
Revises: 8983fa81a3ec
Create Date: 2023-05-26 18:28:56.425394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5c1cd6f0c8'
down_revision = '8983fa81a3ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
