"""empty message

Revision ID: 12a5e00eb3e0
Revises: 76b15018fe31
Create Date: 2023-05-27 19:54:55.094221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a5e00eb3e0'
down_revision = '76b15018fe31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
