"""empty message

Revision ID: 20f4202ab0da
Revises: 3c12154c2cf1
Create Date: 2023-05-27 22:23:20.981785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f4202ab0da'
down_revision = '3c12154c2cf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
