"""empty message

Revision ID: 28e3ef930403
Revises: 7afc2bb7a888
Create Date: 2023-05-27 01:51:32.038321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e3ef930403'
down_revision = '7afc2bb7a888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
