"""empty message

Revision ID: 2a60f634d3ff
Revises: f869370e1b4b
Create Date: 2023-05-26 23:39:01.448681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a60f634d3ff'
down_revision = 'f869370e1b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
