"""empty message

Revision ID: 3b16dc6e91f3
Revises: c147c40621a6
Create Date: 2023-05-28 10:23:58.028817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b16dc6e91f3'
down_revision = 'c147c40621a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
