"""empty message

Revision ID: 3b74af7cff99
Revises: 7528ae221600
Create Date: 2023-05-27 11:25:50.940836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b74af7cff99'
down_revision = '7528ae221600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
