"""empty message

Revision ID: 3c12154c2cf1
Revises: 44ea10a583fd
Create Date: 2023-05-27 22:19:27.459478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c12154c2cf1'
down_revision = '44ea10a583fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
