"""empty message

Revision ID: 4309eb16000f
Revises: d367864cc764
Create Date: 2023-05-27 22:50:44.043741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4309eb16000f'
down_revision = 'd367864cc764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
