"""empty message

Revision ID: 44ea10a583fd
Revises: b6ecb44c4491
Create Date: 2023-05-27 22:16:32.400215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ea10a583fd'
down_revision = 'b6ecb44c4491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
