"""empty message

Revision ID: 4e04bf7b8667
Revises: 77e779daba2c
Create Date: 2023-05-25 23:11:26.315470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e04bf7b8667'
down_revision = '77e779daba2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
