"""empty message

Revision ID: 5aa8eafe9ea0
Revises: 8be5a200d62c
Create Date: 2023-05-26 19:51:00.633620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa8eafe9ea0'
down_revision = '8be5a200d62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
