"""empty message

Revision ID: 6a00239cac5d
Revises: 0d5c1cd6f0c8
Create Date: 2023-05-26 19:35:35.841175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a00239cac5d'
down_revision = '0d5c1cd6f0c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
