"""empty message

Revision ID: 74ae62318fd8
Revises: 92f2a99d172c
Create Date: 2023-05-27 10:16:38.479647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ae62318fd8'
down_revision = '92f2a99d172c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('message', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('message', 'content')
    # ### end Alembic commands ###
