"""empty message

Revision ID: 75ef860b90a6
Revises: 8f6c55e551d9
Create Date: 2023-05-27 01:40:39.296578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ef860b90a6'
down_revision = '8f6c55e551d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
