"""empty message

Revision ID: 76b15018fe31
Revises: 3b74af7cff99
Create Date: 2023-05-27 14:53:34.095723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b15018fe31'
down_revision = '3b74af7cff99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
