"""empty message

Revision ID: 77e779daba2c
Revises: 3d5d20071650
Create Date: 2023-05-25 22:27:27.344966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e779daba2c'
down_revision = '3d5d20071650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
