"""empty message

Revision ID: 81389b961577
Revises: 28e3ef930403
Create Date: 2023-05-27 01:52:35.696317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81389b961577'
down_revision = '28e3ef930403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
