"""empty message

Revision ID: 836461bfa584
Revises: 8aa99788f5c0
Create Date: 2023-05-26 18:01:14.360999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836461bfa584'
down_revision = '8aa99788f5c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problembid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('bidder_id', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problembid_id'), 'problembid', ['id'], unique=False)
    op.create_table('collaborationbid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=True),
    sa.Column('bidder_id', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborationbid_id'), 'collaborationbid', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaborationbid_id'), table_name='collaborationbid')
    op.drop_table('collaborationbid')
    op.drop_index(op.f('ix_problembid_id'), table_name='problembid')
    op.drop_table('problembid')
    # ### end Alembic commands ###
