"""empty message

Revision ID: 8983fa81a3ec
Revises: 836461bfa584
Create Date: 2023-05-26 18:04:31.022818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8983fa81a3ec'
down_revision = '836461bfa584'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collaborationbid', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('collaborationbid', 'bid')
    op.add_column('problembid', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('problembid', 'bid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problembid', sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('problembid', 'description')
    op.add_column('collaborationbid', sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('collaborationbid', 'description')
    # ### end Alembic commands ###
