"""empty message

Revision ID: 89c3c411c60d
Revises: c71613eb0670
Create Date: 2023-05-26 19:56:00.375871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c3c411c60d'
down_revision = 'c71613eb0670'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
