"""empty message

Revision ID: 8aa99788f5c0
Revises: 92679c88912b
Create Date: 2023-05-26 16:37:33.052240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa99788f5c0'
down_revision = '92679c88912b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
