"""empty message

Revision ID: 8be5a200d62c
Revises: 6a00239cac5d
Create Date: 2023-05-26 19:49:28.852897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be5a200d62c'
down_revision = '6a00239cac5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
