"""empty message

Revision ID: 8f6c55e551d9
Revises: 2a60f634d3ff
Create Date: 2023-05-27 01:39:03.653810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6c55e551d9'
down_revision = '2a60f634d3ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
