"""empty message

Revision ID: 92679c88912b
Revises: 4e04bf7b8667
Create Date: 2023-05-26 16:35:11.072188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92679c88912b'
down_revision = '4e04bf7b8667'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
