"""empty message

Revision ID: 92f2a99d172c
Revises: 81389b961577
Create Date: 2023-05-27 01:53:39.186987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f2a99d172c'
down_revision = '81389b961577'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
