"""empty message

Revision ID: 9955589c7818
Revises: 4309eb16000f
Create Date: 2023-05-27 22:54:30.943962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9955589c7818'
down_revision = '4309eb16000f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
