"""empty message

Revision ID: b6ecb44c4491
Revises: 12a5e00eb3e0
Create Date: 2023-05-27 22:11:41.980111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ecb44c4491'
down_revision = '12a5e00eb3e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
