"""empty message

Revision ID: c71613eb0670
Revises: 5aa8eafe9ea0
Create Date: 2023-05-26 19:55:23.517910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71613eb0670'
down_revision = '5aa8eafe9ea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
