"""empty message

Revision ID: d8bd36b3e5e8
Revises: 9955589c7818
Create Date: 2023-05-27 23:54:03.991885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bd36b3e5e8'
down_revision = '9955589c7818'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
